---

########### BANCO DE DADOS ###############
- hosts: database
  roles:
    - mysql

########### WORDPRESS ###############
- hosts: wordpress # Destino de execução
  roles:
    - webserver
    - wordpress   